// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponent: typeof import('./src/components/AsyncComponent.vue')['default']
    ErrorForAsync: typeof import('./src/components/ErrorForAsync.vue')['default']
    LoadingForAsync: typeof import('./src/components/LoadingForAsync.vue')['default']
  }
}

export { }
